### ISSUE TITLE
Come up with 3 design ideas

### ISSUE THREAD

**Issue by stelishDev** [stelishDev/talspot#1]
We need atleast 3 ideas for the talspot web site. Each idea should include:

Acceptance criteria:
1. A brand colour scheme with (primary, secondary, tertiary and neutral colours)
2. A design including header, footer, body design
3. Be mobile responsive

The designs can be a design or a link to another design.

Useful resources:
https://webflow.com/blog/best-websites?utm_source=google&utm_medium=search&utm_campaign=SS-GoogleSearch-Nonbrand-DynamicSearchAds-Tier3&utm_term=dsa-1729073415988___697641339332__&gad_source=1&gclid=Cj0KCQiAx9q6BhCDARIsACwUxu4lC5kvlYUuqm_vAN-SMAHd8SnXDsDs8bYpOmSlweqoBvrg25he6RUaAq3_EALw_wcB

https://www.designrush.com/best-designs/websites

https://coolors.co/

**Comment by jonnykelly1** [comment]
Design 1: 

#1  ![Image](https://github.com/user-attachments/assets/42895147-e550-4c05-930d-aa59a4529162) 

#2  ![Image](https://github.com/user-attachments/assets/da7264fe-a43e-4c4e-bd15-ebc82ca23308)


![Image](https://github.com/user-attachments/assets/63de9343-17ab-4ca5-bb93-a45c13d3a244)

**Comment by jonnykelly1** [comment]
Design 1: 

#1  ![Image](https://github.com/user-attachments/assets/3710b4bf-4a72-415a-9f75-c873306ee2e4) 

#2   ![Image](https://github.com/user-attachments/assets/4028f82a-5058-40f3-9ac9-a15b80ed23e7)

**Comment by jonnykelly1** [comment]
Design 2: 

#1 ![Image](https://github.com/user-attachments/assets/f123c4fd-3af0-46c4-8fcc-9b925181b3b0) 

#2  ![Image](https://github.com/user-attachments/assets/6533c40d-63cb-4dd1-a129-5bd805a68267)

**Comment by jonnykelly1** [comment]
Design 2: 

#1   ![Image](https://github.com/user-attachments/assets/786473d3-0136-49d5-bfc5-8bffa55cc604)


#2  ![Image](https://github.com/user-attachments/assets/5b3341d7-fcb7-4801-898d-383f926844b6)

**Comment by jonnykelly1** [comment]
Design 1: 

#1 ![Image](https://github.com/user-attachments/assets/6f620132-e900-4649-954e-2699a0721358)
 
#2 ![Image](https://github.com/user-attachments/assets/c27a097e-4e77-4755-a872-f1c442d6f746)

**Comment by jonnykelly1** [comment]
![Image](https://github.com/user-attachments/assets/c3bfdc53-0c07-4674-a9eb-776d3fec1a09)
![Image](https://github.com/user-attachments/assets/7a0f6045-8b50-46b1-aa68-b3b3e46930a6)

**Comment by jonnykelly1** [comment]
Design 3: 

![Image](https://github.com/user-attachments/assets/1138a7de-d47b-4a31-8538-71806a94c28e) 

![Image](https://github.com/user-attachments/assets/1b063d7f-a0fa-4175-8ef4-a08ab86c04d5)

**Comment by jonnykelly1** [comment]
Design 1: 
<img width="308" alt="Image" src="https://github.com/user-attachments/assets/ebe366bf-b230-4db2-a941-40917ff502e2" /> 

Design 2: 
<img width="247" alt="Image" src="https://github.com/user-attachments/assets/1312c430-b241-46b9-9ea6-60f1715b4c98" />

Design 3: 
<img width="283" alt="Image" src="https://github.com/user-attachments/assets/2d2d3470-0e90-4163-8231-035bddd478e6" /> 

Design 4: 
<img width="337" alt="Image" src="https://github.com/user-attachments/assets/96a09110-909f-4b9a-bdf7-6080d0f71332" />

**Comment by jonnykelly1** [comment]
Design 3: 
<img width="441" alt="Image" src="https://github.com/user-attachments/assets/4e6fa9fb-26c0-4955-8f61-5b06e3063dd5" /> 

Design 2: 
<img width="251" alt="Image" src="https://github.com/user-attachments/assets/2eb1d663-62df-45fc-a70f-6c87cbe0555e" />

Design 1: 
<img width="226" alt="Image" src="https://github.com/user-attachments/assets/7705aebb-5936-48ff-99f4-7fd26b1dfbc6" />
<img width="251" alt="Image" src="https://github.com/user-attachments/assets/d1fa62eb-f87f-42f5-9618-9b25ce8ed674" />

**Comment by stelishDev** [comment]
Lets go with a combination of design 3 & design 1 : 
<img width="283" alt="Image" src="https://github.com/user-attachments/assets/e6b7ad26-6f45-4172-ac91-8bc85bed1a1b" />
